"""added DeckRating

Revision ID: 7ae4378921af
Revises: e4c58d78d253
Create Date: 2026-05-23 19:29:35.291608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7ae4378921af'
down_revision: Union[str, Sequence[str], None] = 'e4c58d78d253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_rating',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('rater_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'rater_id')
    )
    op.create_index(op.f('ix_deck_rating_deck_id'), 'deck_rating', ['deck_id'], unique=False)
    op.create_index(op.f('ix_deck_rating_rater_id'), 'deck_rating', ['rater_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deck_rating_rater_id'), table_name='deck_rating')
    op.drop_index(op.f('ix_deck_rating_deck_id'), table_name='deck_rating')
    op.drop_table('deck_rating')
    # ### end Alembic commands ###
