"""last_activity_at

Revision ID: 88246a4a01d1
Revises: bdfdfc5eb06f
Create Date: 2026-09-01 01:07:17.544396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88246a4a01d1'
down_revision: Union[str, Sequence[str], None] = 'bdfdfc5eb06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("study_session", sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True))
    op.execute("""
        UPDATE study_session
        SET last_activity_at = started_at
    """)
    op.alter_column("study_session", "last_activity_at", existing_type=sa.DateTime(timezone=True), nullable=False)
    op.create_index(op.f("ix_study_session_last_activity_at"), "study_session", ["last_activity_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_session_last_activity_at'), table_name='study_session')
    op.drop_column('study_session', 'last_activity_at')
    # ### end Alembic commands ###
