"""card review

Revision ID: af395bd352ef
Revises: e4e7534c162c
Create Date: 2026-09-07 00:22:11.985560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af395bd352ef'
down_revision: Union[str, Sequence[str], None] = 'e4e7534c162c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_review', sa.Column('session_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_card_review_session_id'), 'card_review', ['session_id'], unique=False)
    op.create_foreign_key(None, 'card_review', 'study_session', ['session_id'], ['session_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_review', type_='foreignkey')
    op.drop_index(op.f('ix_card_review_session_id'), table_name='card_review')
    op.drop_column('card_review', 'session_id')
    # ### end Alembic commands ###
