"""card_review

Revision ID: bdfdfc5eb06f
Revises: e7ef0c7ff310
Create Date: 2026-08-14 19:01:34.307323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bdfdfc5eb06f'
down_revision: Union[str, Sequence[str], None] = 'e7ef0c7ff310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_review',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=6), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_card_review_card_id'), 'card_review', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_review_reviewed_at'), 'card_review', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_card_review_student_id'), 'card_review', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_review_student_id'), table_name='card_review')
    op.drop_index(op.f('ix_card_review_reviewed_at'), table_name='card_review')
    op.drop_index(op.f('ix_card_review_card_id'), table_name='card_review')
    op.drop_table('card_review')
    # ### end Alembic commands ###
