"""initial

Revision ID: e4c58d78d253
Revises: 
Create Date: 2026-05-22 20:04:37.995224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'e4c58d78d253'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('tag_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('user',
    sa.Column('fname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('deck',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('deck_name', sa.String(length=250), nullable=False),
    sa.Column('creator_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('deck_id')
    )
    op.create_index(op.f('ix_deck_creator_id'), 'deck', ['creator_id'], unique=False)
    op.create_index(op.f('ix_deck_is_public'), 'deck', ['is_public'], unique=False)
    op.create_table('oauth_account',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('card',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('card_term', sa.Text(), nullable=False),
    sa.Column('card_definition', sa.Text(), nullable=False),
    sa.Column('card_term_url', sa.String(length=250), nullable=True),
    sa.Column('card_definition_url', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_card_deck_id'), 'card', ['deck_id'], unique=False)
    op.create_table('deck_tag',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'deck_id')
    )
    op.create_table('room',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('room_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_index(op.f('ix_room_host_id'), 'room', ['host_id'], unique=False)
    op.create_table('study_session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_study_session_deck_id'), 'study_session', ['deck_id'], unique=False)
    op.create_index(op.f('ix_study_session_student_id'), 'study_session', ['student_id'], unique=False)
    op.create_table('card_progress',
    sa.Column('progress_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('current_interval', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('last_rating', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index(op.f('ix_card_progress_card_id'), 'card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_progress_next_review_date'), 'card_progress', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_card_progress_student_id'), 'card_progress', ['student_id'], unique=False)
    op.create_table('room_participant',
    sa.Column('participant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('placement', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'room_id')
    )
    op.create_index(op.f('ix_room_participant_room_id'), 'room_participant', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_participant_room_id'), table_name='room_participant')
    op.drop_table('room_participant')
    op.drop_index(op.f('ix_card_progress_student_id'), table_name='card_progress')
    op.drop_index(op.f('ix_card_progress_next_review_date'), table_name='card_progress')
    op.drop_index(op.f('ix_card_progress_card_id'), table_name='card_progress')
    op.drop_table('card_progress')
    op.drop_index(op.f('ix_study_session_student_id'), table_name='study_session')
    op.drop_index(op.f('ix_study_session_deck_id'), table_name='study_session')
    op.drop_table('study_session')
    op.drop_index(op.f('ix_room_host_id'), table_name='room')
    op.drop_table('room')
    op.drop_table('deck_tag')
    op.drop_index(op.f('ix_card_deck_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_index(op.f('ix_deck_is_public'), table_name='deck')
    op.drop_index(op.f('ix_deck_creator_id'), table_name='deck')
    op.drop_table('deck')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
