"""card term and defintion nullability

Revision ID: e4e7534c162c
Revises: 88246a4a01d1
Create Date: 2026-09-02 21:24:02.745446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4e7534c162c'
down_revision: Union[str, Sequence[str], None] = '88246a4a01d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'card_term',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('card', 'card_definition',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'card_definition',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('card', 'card_term',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
