"""last_review_date

Revision ID: e7ef0c7ff310
Revises: 6ca98b7b7ebf
Create Date: 2026-08-14 12:54:27.821705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ef0c7ff310'
down_revision: Union[str, Sequence[str], None] = '6ca98b7b7ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_progress', sa.Column('last_review_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_card_progress_last_review_date'), 'card_progress', ['last_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_progress_last_review_date'), table_name='card_progress')
    op.drop_column('card_progress', 'last_review_date')
    # ### end Alembic commands ###
